### ISSUE TITLE
NFR form wouldn't submit w SF ID

### ISSUE THREAD

**Issue by nikmac** [DoubleCheck/board#2]
When trying to submit our first sales driven NFR request, the form would not allow us to "create" NFR with OR without entering the salesforce ID.  So I called Matt and had him "disable" validate in nfr_manage.js

**Comment by nikmac** [comment]
"ignore me" not.

**Comment by jaredj** [comment]
Moved to https://efsgithub.securewebportal.net/dc/doublecheck/issues/368
