### ISSUE TITLE
Details page changes

### ISSUE THREAD

**Issue by marksaner** [DoubleCheck/board#3]
The new details page is really hard to read. Changing and removing some things would help as well as maybe adding some color or highlighting. The alternating highlighting of lines helps with viewing as well as having the header on each line be bold. There is also no classify button on the new details page. 

I really like having the Action: and Detail: section in the old details page. I specifically like how the Action matches the action on the log search page and is highlighted in a color specific to delivery success.

See attached screenshot for further comments.

**Comment by marksaner** [comment]
![new-message-details](https://cloud.githubusercontent.com/assets/12202794/10589234/06a888f2-7678-11e5-8f7a-38b03d1b4e94.png)

**Comment by marksaner** [comment]
Also it would be nice to be able to train from the details page as well.

**Comment by jaredj** [comment]
Moved to https://efsgithub.securewebportal.net/dc/webui/issues/357
